### ISSUE TITLE
getGPPData response missing pingData property

### ISSUE THREAD

**Issue by nealrosen** [IABTechLab/iabgpp-es#14]
The [spec](https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/main/Core/CMP%20API%20Specification.md#getgppdata) specifies that the getGPPData command should respond with a pingData property.  That appears to be missing [here](https://github.com/IABTechLab/iabgpp-es/blob/master/modules/cmpapi/src/cmpapi/command/GetGppDataCommand.ts)

**Comment by chuff** [comment]
Fixed in 3.0.6
