### ISSUE TITLE
GPP API v1.1

### ISSUE THREAD

**Issue by taraschi-sp** [IABTechLab/iabgpp-es#28]
Will this package be updated to support v1.1 of the GPP API (changes outlined in this pr - https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/pull/70)

**Comment by lamrowena** [comment]
Yes, this will be updated shortly following finalization

**Comment by nejcsever** [comment]
Hi, is there any time estimate for when this will be available?
