### ISSUE TITLE
JS exception on Edge iOS related to support for Sets

### ISSUE THREAD

**Issue by nealrosen** [IABTechLab/iabgpp-es#44]
It seems Edge iOS does not supports Sets as iterable.  This results in the script error
```
Uncaught TypeError: Set is not a function or its return value is not iterable
    at s.setValue (cmp.js:2:32561)
    at new s (cmp.js:2:32147)
    at new a (cmp.js:2:61891)
    at t.GppModel.decode (cmp.js:2:27797)
    at t.CmpApi.setGppString (cmp.js:2:6667)
    ....
```

This limitation appears to be undocumented, at least not something you'll find on MDN or [caniuse.com](http://caniuse.com/).

A potential fix would be to create a utility function to support this
```
function setToArray<T>(set: Set<T>): T[] {
  const arr: T[] = [];
  set.forEach(item => arr.push(item));
  return arr;
}
```

**Comment by HeinzBaumann** [comment]
Which version of Edge version is this? Based on MDN Set is supported starting Edge 12.

**Comment by nealrosen** [comment]
It turns out this report came from someone testing with dev tools on Mac OS when emulating mobile.  The reporter did not see an issue on his actual iOS device.  Closing this issue.
