### ISSUE TITLE
Issue with PublisherRestrictions in TCF String Causing Invalid GPP String

### ISSUE THREAD

**Issue by kamdishantanu** [IABTechLab/iabgpp-es#69]
Description:
I am encountering an issue while using setSectionString with a TCF string created using the @iabtechlabtcf/core library. The TCF string includes PublisherRestrictions. However, when this TCF string is processed, the resulting GPP string is invalid.

Details:

TCF String with PublisherRestrictions:
`CQJHBMAQJHBMAAKA4AENBSFsAP_AAEPAAAwIKqNX_G__bXlrcX736ftkeY1f9_h77sQhBhfJE-4FzLvW_JwX32EzNA36tqIKmRIAu3TBIQNlGJDURVCgaogVrzDMaEyUoTtKJ6BkiFMRc2dYCFxvm4tj-QCY5vr991d52R-p7dr83dzyy4xnv3a9_2S1WJCdA5-tDfv9bROb-9IO9_x8v4v4_NdpE2_eT1l_tWvp7D9-ctv__XX99_fff_9Pn_-uB_-_3_vb_EFU0CzDRqpoyydLQokCiCBESoK4gYoEAYAAJg2QECZk0KdgYAJ7CZACCFAAMEDIAAQJgAgAAkgAQqAiAQpUAAkAB0AAYAEAgEAXAwABiIkBAIACQHwcUwAIBIsQErOCok4AwiEgkpbChBIAgAx4hSLPAKgAxMFAGADQAEgACAsDAeCbAtZkFEXEb0gQBAAgmlkBQil7sIQUjOy1X4MG0bWmBYNmA57TBNkDIKycAYKBeAACAAoADYAIoATgBUADsAHoAQgAigBOACkAF4AOYAigBKgCuAGJAM4A0QBwADjAHWAPEAhABHQCTAE6gK8Ar4BfgDbAHAAObAdcB2QD1AHtAP2AiYBHcCWgJiAUIApKBTIFNAKlAV8AskBaIC3QF0ALsAXoAv4BhADGQGOAMeAakA1oBrwDZQHHAOWgdSB1QDtwH2AP4AgEBAUCBwEFwITwQ3BDiCHQIdgRCAiSBGaCNQI2ARvgjiCOUEjQSPAksBJ4CVwEsgJdATKAm8BOECdAFDAKSAUrApiBT0CpAFSyYDwAAIAIoATgBQAEIAKQAdwBiADgAHGAOsAjIBOoCvAK-AX4AzgBtgDgAHNgP2A_gCOQEvAKEAUgApIBTICpAFZALWgW6BbwC7AF6AMZAY8A1IBrQDZQHAAOOAfEA-wCAoEDgILgQjAhwBDoCIUEagRsgjiCOQEdQJHgSWAk8BKsCVwEtgJigTKAnQBO0dB7AAXABQAFQAOAAggBcAGoAPAAiABMACmAFWALgAugBiADeAHoAP0AhgCJAEsAJoATgAowBWgDAAGGAMoAaIA2QBzwDuAO-AewB8QD7AP0Af8BFAEYgI6AksBPwFBgKiAq4BYgC5wF5AXoAxQBtADcAHEAOoAfYBCACHQETgIvgR6BIoCZAE7AKHgUeBSACk4FNAU2AqwBYoC2AFugLgAXIAu0Bd4C8wF9AMNAY9AyMDJAGTgMqgZYBlwDMwGcgNNAarA1cDWAG0ANvAbqA4sByYDlwHjgPaAfWA-4B_YD_gIAgQYAhaBDoCHsEfQR_AkUBJACTMEswS0Al0BL4CYAEzAJnATVAm4BN4CcIE5gJ0wTtBO4CeAE8wKDAUIAoWBRICioFJQKXAU8AqMBUoCpxCBsAAsACgALgAagBVAC4AGIAN4AegBHADAAHPAO4A7wB_gEUAJSAUGAqICrgFzAMUAbQA6gCJwEegKTgU0BTYCrAFigLRAXAAuQBkYDJwGcgNVAeOA_sCDAELQIdAQ9AkUBJACXQEzgJzATuAngBPMCgwFFQKSgUuAqUUgwgALgAoACoAHAAQQAyADQAHgARAAmABSACqAGIAP0AhgCJAFGAK0AYAAygBogDZAHOAO-AfYB-gEWAIxAR0BJQCgwFRAVcAuYBeQDFAG0ANwAdQA9oB9gEOwImAicBF8CPQJFATsAocBSACk4FNAU2AqwBYoC2AFwALkAXaAvMBfQDDYGRgZIAyeBlgGXAM5gawBrIDbwG6gOCAcmA8UB44D2gH9gP-AgmBBgCEIELQIZwQ5BDqCPoI_gSKAkhBJgEmQJZgS6Al8BMACZgEzgJqgTeAnMBO4CeAE8wKFgUVApKBS4CngFRgKlAVOLQEwAagDAAHcAXoA-wCh4FNAU2AqwBmYDxwIegTMAm4BOYCdwE8AKSAUuAqUA.YAAAAAAAAAAA.IKqNX_G__bXlv-X736ftkeY1f9_h77sQxBhfJs-4FzLvW_JwX32EzNE36tqYKmRIAu3TBIQNtGJjURVChaogVrzDsaEyUoTtKJ-BkiHMRc2dYCFxvm4tj-QCZ5vr_91d52R_t7dr-3dzyy5xnv3a9_-S1WJidK5-tH_v9bROb-_I-9_x-_4v4_N_pE2_eT1t_tWvt739-8tv____99___________3_-____f_8A`

Equivalent GPP String:
`DBABMA~CQJHBMAQJHBMAAKA4AENBSFsAP_AAEPAAAwIKqNX_G__bXlrcX736ftkeY1f9_h77sQhBhfJE-4FzLvW_JwX32EzNA36tqIKmRIAu3TBIQNlGJDURVCgaogVrzDMaEyUoTtKJ6BkiFMRc2dYCFxvm4tj-QCY5vr991d52R-p7dr83dzyy4xnv3a9_2S1WJCdA5-tDfv9bROb-9IO9_x8v4v4_NdpE2_eT1l_tWvp7D9-ctv__XX99_fff_9Pn_-uB_-_3_vb_EFU0CzDRqpoyydLQokCiCBESoK4gYoEAYAAJg2QECZk0KdgYAJ7CZACCFAAMEDIAAQJgAgAAkgAQqAiAQpUAAkAB0AAYAEAgEAXAwABiIkBAIACQHwcUwAIBIsQErOCok4AwiEgkpbChBIAgAx4hSLPAKgAxMFAGADQAEgACAsDAeCbAtZkFEXEb0gQBAAgmlkBQil7sIQUjOy1X4MG0bWmBYNmA57TBNkDIKycAKAAYAEQAKAAsAAA.YAAAAAAAAAAA`

Could you provide insights into why this might be happening and how to resolve the issue?

**Comment by HeinzBaumann** [comment]
I believe you will need to use the corresponding library for GPP to set the TCF section in GPP. Regarding the publisher restriction, they are a little differently encoded in CPP than in TCF standalone. Therefore it is important to use the GPP library to set this section string.

**Comment by kamdishantanu** [comment]
Will try new version. Thanks.
